'use strict';

const axios = require('axios');
const fs = require('fs');
const path = require('path');
const excludeGames = JSON.parse(fs.readFileSync(path.join(__dirname, '../assets/exclude_games.json')));
const configStatic = JSON.parse(fs.readFileSync(path.join(__dirname, '../assets/config_static.json')));

/**
 * Converts a JS string array to a C++ string array initializer list.
 * @param {string[]} arr
 * @returns {string}
 */
function toCppStringArray(arr) {
    return arr.map(s => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`).join(',');
}

/**
 * Generates the full Config.cpp content from the games list and static config.
 * @param {string[]} games
 * @param {object} staticConfig
 * @returns {string}
 */
function generateConfigCpp(games, staticConfig) {
    return `// Config.cpp - Auto-generated by js/parse_games.js - DO NOT EDIT MANUALLY
#include <string>
#include "Config.h"

using namespace std;

string games[] = { ${toCppStringArray(games)} };
string allCoreNoVCacheGames[] = { ${toCppStringArray(staticConfig.allCoreNoVCacheGames)} };
string cacheGames[] = { ${toCppStringArray(staticConfig.cacheGames)} };
string services[] = { ${toCppStringArray(staticConfig.services)} };
`;
}

axios.get('https://discord.com/api/v10/applications/detectable').then(({status, data}) => {
    if (200 !== status) {
        throw new Error('Fetching games failed');
    }

    fs.writeFileSync(path.join(__dirname, '../assets/games_raw.json'), JSON.stringify(data));

    const games = [];
    const exeToNameMap = {};
    for (let game of data)
    {
        if (game.executables) {
            for (let executable of game.executables)
            {
                if (executable.os !== 'win32')
                {
                    continue;
                }

                let exeName = executable.name.split('/').pop();

                if (games.includes(exeName) || excludeGames.includes(exeName))
                {
                    continue;
                }

                games.push(exeName);

                exeToNameMap[exeName] = game.name;
            }
        }
    }

    for (let game of JSON.parse(fs.readFileSync(path.join(__dirname, '../assets/additional_games.json'))))
    {
        if (games.includes(game))
        {
            continue;
        }

        games.push(game);
    }

    const gameNames = [];
    let gamesCount = 0;
    let gamesList = `# Supported games
\rCurrently supported games: [SUPPORTED_GAMES]\n\rYou can now search the supported games on our website: [Search Games](https://exatek.de/products/exa-game-booster)`;
    for (let game of games)
    {
        if (!exeToNameMap[game])
        {
            continue;
        }

        if (gameNames.includes(exeToNameMap[game]))
        {
            continue;
        }

        gameNames.push(exeToNameMap[game]);
    }

    gameNames.sort();

    for (let gameName of gameNames)
    {
        gamesCount++;
    }

    fs.writeFileSync(path.join(__dirname, '../supportedGames.md'), gamesList.replace('[SUPPORTED_GAMES]', String(gamesCount)));
    fs.writeFileSync(path.join(__dirname, '../assets/games.json'), JSON.stringify(games));
    fs.writeFileSync(path.join(__dirname, '../assets/game_names.json'), JSON.stringify(gameNames));
    fs.writeFileSync(path.join(__dirname, '../src/ExaGameBooster/Config.cpp'), generateConfigCpp(games, configStatic));

    console.log(`Config.cpp written with ${games.length} games.`);
});
